########################

version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.0 #imports the s3 orb in the circleci namespace

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/whatsupp

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # install pip
      - run:
          name: Install dependencies
          command: sudo apt install python-pip python-dev

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      # build
      - run: yarn build

      - persist_to_workspace:
          root: ~/whatsupp
          paths:
            - public

  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3

    steps:
      # install pip
      - run:
          name: Install dependencies
          command: sudo apt install python-pip python-dev

      - aws-s3/sync:
          from: ~/whatsapp/public/
          to: "s3://whatsupp"
          overwrite: true

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
